version: 2.0
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.9.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: pip install --user -r requirements.txt
      - run:
          name: Run Unit Test On Submit Button Text
          command: python test.py

  deploy:
    docker:
      - image: circleci/python:3.9.4
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main
    
workflows:
  version: 2
  build_test:
    jobs:
      - run_tests
      - deploy:
          requires:
            - run_tests
          filters:
             branches:
               only: main





