version: 2.0
jobs:
  run_tests:
    docker:
      - image: circleci/python:3.9.4
        environment:
          PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: pip install --user -r requirements.txt
      - run:
          name: Run Unit Test
          command: |
            flask run
            python test.py
  
workflows:
  version: 2
  build_test:
    jobs:
      - run_tests





